apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-p6yc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-twmx-tenant/rhtap-demo-app/hacbs-test-project-p6yc@sha256:6550cec6e491e25b691de237e923afd608313b4c5ada17ac42f48db07d17a2d1
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
