apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-p6yc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-p6yc
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-p6yc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-p6yc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-p6yc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-twmx-tenant/rhtap-demo-app/hacbs-test-project-p6yc@sha256:6550cec6e491e25b691de237e923afd608313b4c5ada17ac42f48db07d17a2d1
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
